spring:
  security:
    user:
      name: sagar
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_KEY}
            scope: # which data to retrieve
              - profile
              - email
